In [1]:
# Libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier


In [2]:
import pandas as pd

# Load data from CSV
file_path = "E:/DEPI/tasks/seployment assignment/Target_Severity_Score as classification/global_cancer_patients_2015_2024.csv"  # حط هنا مسار الملف
df = pd.read_csv(file_path)

df.head()

Patient_ID  Age  Gender Country_Region  Year  Genetic_Risk  Air_Pollution  \
0  PT0000000   71    Male             UK  2021           6.4            2.8   
1  PT0000001   34    Male          China  2021           1.3            4.5   
2  PT0000002   80    Male       Pakistan  2023           7.4            7.9   
3  PT0000003   40    Male             UK  2015           1.7            2.9   
4  PT0000004   43  Female         Brazil  2017           5.1            2.8   

   Alcohol_Use  Smoking  Obesity_Level Cancer_Type Cancer_Stage  \
0          9.5      0.9            8.7        Lung    Stage III   
1          3.7      3.9            6.3    Leukemia      Stage 0   
2          2.4      4.7            0.1      Breast     Stage II   
3          4.8      3.5            2.7       Colon      Stage I   
4          2.3      6.7            0.5        Skin    Stage III   

   Treatment_Cost_USD  Survival_Years  Target_Severity_Score  
0            62913.44             5.9                   4.92  
1            12573.41             4.7                   4.65  
2             6984.33             7.1                   5.84  
3            67446.25             1.6                   3.12  
4            77977.12             2.9                   3.62

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Patient_ID             50000 non-null  object 
 1   Age                    50000 non-null  int64  
 2   Gender                 50000 non-null  object 
 3   Country_Region         50000 non-null  object 
 4   Year                   50000 non-null  int64  
 5   Genetic_Risk           50000 non-null  float64
 6   Air_Pollution          50000 non-null  float64
 7   Alcohol_Use            50000 non-null  float64
 8   Smoking                50000 non-null  float64
 9   Obesity_Level          50000 non-null  float64
 10  Cancer_Type            50000 non-null  object 
 11  Cancer_Stage           50000 non-null  object 
 12  Treatment_Cost_USD     50000 non-null  float64
 13  Survival_Years         50000 non-null  float64
 14  Target_Severity_Score  50000 non-null  float64
dtypes:

In [4]:
df.columns

Index(['Patient_ID', 'Age', 'Gender', 'Country_Region', 'Year', 'Genetic_Risk',
       'Air_Pollution', 'Alcohol_Use', 'Smoking', 'Obesity_Level',
       'Cancer_Type', 'Cancer_Stage', 'Treatment_Cost_USD', 'Survival_Years',
       'Target_Severity_Score'],
      dtype='object')

In [5]:
import pandas as pd

# افترض الداتا محملة في df

# تحديد الأعمدة من نوع object
obj_columns = df.select_dtypes(include='object').columns
print("Object columns:", obj_columns)

# عرض القيم الفريدة لكل عمود
for col in obj_columns:
    unique_values = df[col].unique()
    print(f"\nColumn: {col}")
    print(unique_values)


Object columns: Index(['Patient_ID', 'Gender', 'Country_Region', 'Cancer_Type',
       'Cancer_Stage'],
      dtype='object')

Column: Patient_ID
['PT0000000' 'PT0000001' 'PT0000002' ... 'PT0049997' 'PT0049998'
 'PT0049999']

Column: Gender
['Male' 'Female' 'Other']

Column: Country_Region
['UK' 'China' 'Pakistan' 'Brazil' 'Germany' 'Canada' 'USA' 'India'
 'Australia' 'Russia']

Column: Cancer_Type
['Lung' 'Leukemia' 'Breast' 'Colon' 'Skin' 'Cervical' 'Prostate' 'Liver']

Column: Cancer_Stage
['Stage III' 'Stage 0' 'Stage II' 'Stage I' 'Stage IV']


In [6]:
def fix_gender(row):
    if row['Gender'] != 'Other':
        return row['Gender']
    # قواعد تحديد الجنس حسب نوع السرطان
    if row['Cancer_Type'] in ['Breast', 'Cervical']:
        return 'Female'
    elif row['Cancer_Type'] in ['Prostate']:
        return 'Male'
    else:
        return 'Other'  # لو مش عايز تغير الباقي

df['Gender'] = df.apply(fix_gender, axis=1)

# التأكد
print(df['Gender'].unique())


['Male' 'Female' 'Other']


In [7]:
df = df.drop(['Patient_ID','Age', 'Year'], axis=1)


In [8]:
import pandas as pd

# مثال على DataFrame
# df = pd.read_csv("your_file.csv")

def convert_score(value):
    if value < 3:
        return 0
    elif value < 6:
        return 1
    elif value < 10:
        return 2

df["Target_Severity_Score"] = df["Target_Severity_Score"].apply(convert_score)


In [9]:
df["Target_Severity_Score"].head()

0    1
1    1
2    1
3    1
4    1
Name: Target_Severity_Score, dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Gender                 50000 non-null  object 
 1   Country_Region         50000 non-null  object 
 2   Genetic_Risk           50000 non-null  float64
 3   Air_Pollution          50000 non-null  float64
 4   Alcohol_Use            50000 non-null  float64
 5   Smoking                50000 non-null  float64
 6   Obesity_Level          50000 non-null  float64
 7   Cancer_Type            50000 non-null  object 
 8   Cancer_Stage           50000 non-null  object 
 9   Treatment_Cost_USD     50000 non-null  float64
 10  Survival_Years         50000 non-null  float64
 11  Target_Severity_Score  50000 non-null  int64  
dtypes: float64(7), int64(1), object(4)
memory usage: 4.6+ MB


In [12]:
numerical_features = df.select_dtypes(include=['int64', 'float64']).columns

numerical_features = numerical_features.drop("Target_Severity_Score")

X = df[numerical_features]
y = df["Target_Severity_Score"]


In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.1, random_state=42, stratify=y)  # stratify للحفاظ على توزيع ال-classes


numeric_cols = X.select_dtypes(include=['int64','float64']).columns.tolist()
scaler = StandardScaler()

X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test_scaled[numeric_cols] = scaler.transform(X_test[numeric_cols])

print("Train/Test split done!")
print("X_train shape:", X_train_scaled.shape)
print("X_test shape:", X_test_scaled.shape)


Train/Test split done!
X_train shape: (45000, 7)
X_test shape: (5000, 7)


In [14]:
X_train_scaled.to_csv("X_train.csv", index=False)
y_train.to_csv("y_train.csv", index=False)

X_test_scaled.to_csv("X_test.csv", index=False)
y_test.to_csv("y_test.csv", index=False)

print("✅ Train/Test datasets saved successfully as CSV files!")


✅ Train/Test datasets saved successfully as CSV files!


In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# إنشاء النموذج
log_model = LogisticRegression(
    multi_class='multinomial',  # للتعامل مع أكثر من فئتين
    solver='lbfgs',             # مناسب للـ multinomial
    max_iter=1000,              # لضمان التقارب
    random_state=42
)

# تدريب النموذج
log_model.fit(X_train_scaled, y_train)

# التنبؤ
y_pred = log_model.predict(X_test_scaled)

# تقييم النموذج
print("✅ Model trained successfully!\n")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


✅ Model trained successfully!

Accuracy: 0.9986

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.99      0.99       259
           1       1.00      1.00      1.00      3749
           2       1.00      1.00      1.00       992

    accuracy                           1.00      5000
   macro avg       1.00      1.00      1.00      5000
weighted avg       1.00      1.00      1.00      5000


Confusion Matrix:
 [[ 256    3    0]
 [   0 3748    1]
 [   0    3  989]]


In [19]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# إنشاء النموذج
xgb_model = XGBClassifier(
    n_estimators=200,        # عدد الأشجار
    learning_rate=0.1,       # معدل التعلم
    max_depth=6,             # عمق كل شجرة
    subsample=0.8,           # نسبة البيانات لكل شجرة (لتقليل overfitting)
    colsample_bytree=0.8,    # نسبة الأعمدة لكل شجرة
    objective='multi:softmax', # لأن عندنا أكثر من فئة
    num_class=3,             # عدد الفئات (0, 1, 2)
    random_state=42,
    use_label_encoder=False, # لتجنب تحذير قديم
    eval_metric='mlogloss'   # metric مناسبة للتصنيف المتعدد
)

# تدريب النموذج
xgb_model.fit(X_train_scaled, y_train)

# التنبؤ
y_pred_xgb = xgb_model.predict(X_test_scaled)

# التقييم
print("✅ XGBoost Model Trained Successfully!\n")
print("🔹 Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("\n🔹 Classification Report:\n", classification_report(y_test, y_pred_xgb))
print("\n🔹 Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))


C:\Users\DELL\anaconda3\envs\tf\lib\site-packages\xgboost\core.py:158: UserWarning: [16:14:33] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-08cbc0333d8d4aae1-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


✅ XGBoost Model Trained Successfully!

🔹 Accuracy: 0.9746

🔹 Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.85      0.91       259
           1       0.97      0.99      0.98      3749
           2       0.99      0.93      0.96       992

    accuracy                           0.97      5000
   macro avg       0.98      0.92      0.95      5000
weighted avg       0.97      0.97      0.97      5000


🔹 Confusion Matrix:
 [[ 219   40    0]
 [   5 3730   14]
 [   0   68  924]]


In [20]:
import pandas as pd

# إنشاء DataFrame للمقارنة بين القيم الفعلية والمتنبأ بها
comparison = pd.DataFrame({
    'Actual': y_test.values[:5],
    'Predicted': y_pred[:5]
})

print(comparison)


🔹 أول خمس قيم من التنبؤ:
   Actual  Predicted
0       1          1
1       1          1
2       1          1
3       1          1
4       0          0
